export const ModelData = {
  mercury: {
    type: "nasa",

    scale: 0.005,

    ui: {
      info: "Mercury—the smallest planet in our solar system and nearest to the Sun—is only slightly larger than Earth's Moon. Mercury lacks a substantial atmosphere, which means it has no protective shield against the Sun's harsh radiation and solar winds. As a result, its surface is pockmarked with countless impact craters, and it experiences extreme temperature variations. ",

      location: [
        {
          name: "Caloris Basin",

          sub_name: "Crater",

          lat: 30.5,

          lon: -106,

          img: "caloris basin.webp",

          script:
            "Mercury does not have a thick atmosphere to protect it from space debris. The small planet is riddled with craters, but none as spectacular as the Caloris Basin. “Basin” is what geologists call craters larger than about 186 miles (300 kilometres) in diameter. Caloris is about 950 miles (1,525 kilometres) across and is ringed by mile-high mountains. For scale, the state of Texas is 773 miles (1,244 kilometres) wide from east to west. ",
        },
        {
          name: "North Pole",

          sub_name: "Pole",

          lat: 90,

          lon: 0,

          img: "mercury north pole.jpg",

          script:
            "Welcome to the cool (literally!) and enigmatic North Pole of Mercury! Here, you'll find the ultimate winter wonderland of the solar system. Despite the planet's scorching surface temperatures, these polar regions hide pockets of ice in permanently shadowed craters—a true cosmic ice rink.",
        },
        {
          name: "Mercury In Color",

          sub_name: "Mercury In Color",

          img: "mercury in color.jpg",

          script:
            "Does the mercury have different colours? Well, not really. Planets have colours from how the materials they are made of reflect light. The colour image was generated by combining three separate images taken through filters sensitive to light in different wavelengths. This was the first high-resolution image of mercury by a spacecraft in over 30-years. ",
        },
      ],

      temperature: {
        min: -170,

        max: 449,

        mean: 167,

        unit: "°C",
      },

      minerals: [
        "Crust : Surface of silicate rocks",

        "Mantle : Solid Silicate Rock",

        "Core : Molten Iron",
      ],

      gases: {
        "O₂": 42,

        Na: 22,

        "H₂": 22,

        He: 6,

        Other: 8,
      },

      satellite: [0, "No Satellite"],
    },
  },
  venus: {
    type: "nasa",

    // r: 300,

    scale: 0.005,

    ui: {
      info: "It's a cloud-swaddled planet named for a love goddess, and often called Earth’s twin. But pull up a bit closer, and Venus turns hellish. Our nearest planetary neighbour, the second planet from the Sun, has a surface hot enough to melt lead. The atmosphere is so thick that, from the surface, the Sun is just a smear of light. ",

      location: [
        {
          name: "Quetzalpetlatl Corona",

          sub_name: "Volcano",

          lat: -68,

          lon: 357,

          img: "Quetzalpetlatl Corona.webp",

          script:
            "Step into the cosmic art gallery and behold the Quetzalpetlatl Corona on Venus! Picture a swirling, majestic crown of volcanic peaks and rifts, etched into the planet's fiery surface. This remarkable feature, with its jumbled terrain and volcanic history, is a puzzle waiting to be explored by future space tourists. ",
        },
        {
          name: "Maat Mons",

          sub_name: "Volcano",

          lat: 0.5,

          lon: 194.6,

          img: "maat mons.jpg",

          script:
            "Hey there, interplanetary travellers! Meet Maat Mons, the rockstar of Venusian volcanoes. Standing tall at about 5 miles (8 kilometres), Maat Mons is a geological giant with a volcanic history that's hotter than a summer day on Venus. Prepare for a journey to a fiery peak with lava flows that will make your Earthly volcanoes blush. ",
        },
        {
          name: "Mead Crater",

          sub_name: "Crater",

          lat: 12.5,

          lon: 57.2,

          img: "mead crater venus.png",

          script:
            "Welcome to Mead Crater on Venus, where cosmic history is etched in impact scars! This massive bowl, roughly 170 miles (280 kilometres) wide, is like the granddaddy of all potholes. It's a reminder of our solar system's tumultuous past. The Magellan science team named this crater Mead, after Margaret Mead, the American Anthropologist",
        },
      ],

      temperature: {
        min: 482,

        max: 438,

        mean: 464,

        unit: "°C",
      },

      minerals: [
        "Crust : Basalt",

        "Mantle : Solid silicate rock",

        "Outer Core : Liquid Iron and Nickel",

        "Inner Core : Dense solid iron and Nickel",
      ],

      gases: {
        "CO₂": 96,

        "N₂": 4,
      },

      satellite: [0, "No Satellite"],
    },
  },

  earth: {
    type: "nasa",

    scale: 0.005,

    ui: {
      info: "Earth, the third planet from the Sun, is the only known celestial body to support life in our solar system. It is often called the 'Blue Planet' due to its abundant water, covering about 71% of its surface. Earth is unique for its diverse ecosystems, including lush forests, vast oceans, and desolate deserts, all harbouring a rich variety of life forms. ",
      location: [
        {
          name: "Mt. Everest",

          sub_name: "Mountain",

          lat: 27.9881,

          lon: 86.925,

          img: "sagarmatha.jpg",

          script: "Allow me to introduce you to the ultimate Earthly peak—Mount Everest. It's like our planet's towering challenge, standing at a jaw-dropping 29,032 feet (8,849 meters) above sea level. Climbing this colossal giant is a dream for daredevils and nature enthusiasts alike. ",
        },

        {
          name: "Grand Canyon",

          sub_name: "Canyon",

          lat: 36.107,

          lon: -112.113,

          img: "grand_canyon.jpg",

          script: " Prepare to be wowed by Earth's natural masterpiece—the Grand Canyon. It's like Mother Nature's epic sculpture, carved by the Colorado River over millions of years, stretching for 277 miles (446 kilometers) and plunging a mile (1.6 kilometers) deep. This colossal chasm is a geologic wonder, revealing Earth's history layer by layer.",
        },

        {
          name: "Pacific Ocean",

          sub_name: "Ocean",

          lat: 0.11, 

          lon: -130.57,

          img: "pacific ocean.jpg",

          script: " Brace yourselves for the Pacific Ocean, Earth's aquatic superstar—it's like the oceanic 'outback' of our blue planet. Stretching over 60 million square miles (155 million square kilometers), this immense expanse is teeming with marine marvels, from vibrant coral reefs to mysterious deep-sea trenches. Dive into this watery wonderland during your planetary pitstop",
        },
      ],

      temperature: {
        min: -89,
        max: 58,
        mean: 15,
        unit: "°C",
      },

      minerals: ["Iron", "Silicon", "Gold", "Copper"],

      gases: {
        "O₂": 21,

        "N₂": 78,

        other: 1,
      },

      satellite: [1, "Moon"],
    },
  },

  moon: {
    type: "nasa",

    scale: 0.005,

    ui: {
      info: "The Moon, Earth's only natural satellite, has fascinated humanity for millennia. It's the fifth-largest moon in the solar system and is about 1/6th the size of Earth. One fascinating aspect is the synchronous rotation, where the same face of the Moon is always visible from Earth, a phenomenon known as 'tidal locking.' ",

      location: [
        {
          name: "Apollo 11 Landing Site",

          sub_name: "Landing Site",

          lat: 0.67416,

          lon: 109,

          img: "apollo 11 landing site.jpg",

          script:
            "Hey future lunar explorers! Welcome to the moon's blockbuster stage—Apollo 11's historic landing site! This is where Neil Armstrong and Buzz Aldrin rocked the first moonwalk in 1969, leaving footprints and a lunar module named 'Eagle' as a testament to human ingenuity. Imagine stepping into their cosmic shoes, feeling the awe of this celestial movie set. Your lunar adventure begins here, where history and the moon collide!",
        },
        {
          name: "NASA Lunar Base Concept",

          sub_name: "Base Concept",

          img: "lunar base concept.jpg",

          script:
            "Get ready for NASA's lunar base! It's like a cosmic vacation home on the moon, where astronauts will live, work, and conduct exciting experiments. This base is our stepping stone to deeper space exploration, like Mars! Imagine stargazing from the lunar surface – it's a real-life space adventure waiting to happen. ",
        },
        {
          name: "Lunar Water",

          sub_name: "Water source",

          img: "lunar water.jpg",

          script:
            "Guess what, future space tourists? Scientists recently found water on the moon—yes, the moon! Not just in dusty corners but trapped in ice near the lunar poles. It's like an interstellar refreshment stand waiting for us, providing drinking water and even rocket fuel for our cosmic adventures ",
        },
      ],

      temperature: {
        min: -173,

        max: 127,

        mean: 120,

        unit: "°C",
      },

      gases: {
        Ar: 70,

        Na: 1,

        He: 29,
      },
    },
  },
  mars: {
    type: "nasa",

    scale: 0.005,

    ui: {
      info: "Mars, often referred to as the 'Red Planet' due to its reddish appearance, is the fourth planet from the Sun and the second smallest in our solar system. It has long captured human imagination as a potential destination for future colonization. Mars is home to the largest volcano in the solar system, Olympus Mons, and a vast canyon system known as Valles Marineris, both of which are dramatic features on its surface. ",

      location: [
        {
          name: "Olympus Mons",

          sub_name: "Volcano",

          lat: 18.5,

          lon: -42.3,

          img: "olympus mons.jpg",

          script:
            "Olympus Mons, the crown jewel of Mars, is a colossal volcano that's truly out of this world! Standing at a towering 72,000 feet (21.9 kilometres), it's the tallest volcano in our solar system. Imagine skiing down slopes that stretch for hundreds of miles! But don't forget your spacesuit – with its otherworldly charm, this Martian giant is a must-see for any aspiring space tourist. ",
        },

        {
          name: "Valles Marineris",

          sub_name: "Canyon",

          lat: -10.9,

          lon: 22.8,

          img: "valles marineris.jpg",

          script:
            "Welcome to Valles Marineris, Mars' own Grand Canyon on steroids! This colossal trench stretches for over 2,500 miles (4,000 kilometres) and plunges as deep as 7 miles (11 kilometres). It's like the ultimate thrill ride for space tourists, offering breathtaking Martian vistas and geological wonders. ",
        },

        {
          name: "Hellas Planitia",

          sub_name: "Crater",

          lat: 40.4,

          lon: 160.5,

          img: "hellas planitia.jpg",

          script:
            "Welcome to Hellas Planitia, the Martian's very own 'Great Basin'! Picture an epic crater, so vast it could fit the entire country of France. With a diameter of about 1,400 miles and a depth reaching the lowest elevations on Mars, Hellas is one of the largest impact craters in the solar system. There has also been evidences that the ground here is rich with ice. ",
        },
      ],

      temperature: {
        min: -125,

        max: 20,

        mean: -65,

        unit: "°C",
      },

      minerals: ["Iron Oxide (Rust)", "Silica", "Sulfur", "Hematite"],

      gases: {
        "CO₂": 95,

        "N₂": 2.7,

        Ar: 1.6,

        other: 0.7,
      },

      satellite: [2, "Deimos", "Phobos"],
    },
  },

  jupiter: {
    type: "nasa",

    scale: 0.005,

    ui: {
      info: "Jupiter, the largest planet in our solar system, is a gas giant known for its massive size and distinctive banded appearance. Its most famous feature is the Great Red Spot, a colossal storm system that has raged for centuries and is larger than Earth. Jupiter's immense gravity exerts a powerful influence on the solar system, helping to protect inner planets like Earth from potentially harmful celestial objects. ",

      location: [
        {
          name: "The Great Red Spot",

          sub_name: "Storm",

          lat: -14,

          lon: 100,

          img: "great red spot.webp",

          script:
            "Howdy, future space wanderers! Meet Jupiter's Great Red Spot, the ultimate storm on the gas giant. This colossal tempest is like the OG of hurricanes—spinning for centuries and wider than our whole planet! So, grab your space umbrellas and witness this mind-blowing whirlwind—it's the ultimate show in our solar system's weather theatre! ",
        },
        {
          name: "Jupiter's Interior",

          sub_name: "Structure",

          img: "jupiter with no land.webp",

          script:
            "Jupiter can be thought of as a giant cosmic cake with layers that are out of this world. At the top, we have the cloud layer, made of colourful bands of gas and storms, including the famous Great Red Spot. Below that, it gets a bit soupy with dense layers of hydrogen and helium. And as you dig deeper, things get wild with metallic hydrogen that generates the planet's immense magnetic field. So, get ready to slice through Jupiter's layers on your interstellar dessert adventure! ",
        },
        {
          name: "High Above Jupiter's Sky",

          sub_name: "Sky",

          img: "high above jupiters sky.webp",

          script:
            "Welcome to the wild, wacky skies of Jupiter. A mesmerizing swirl of colours and chaos. You've got stormy clouds that could swallow Earth whole, electric lightning shows that could put the lightning we have seen till now to shame, and even some mighty auroras dancing overhead. So, don't forget your camera, because Jupiter's sky is like a celestial circus of amazement! ",
        },
      ],

      temperature: {
        mean: -110,

        unit: "°C",
      },

      minerals: ["Hydrogen", "Helium"],

      gases: {
        "H₂": 89.8,

        He: 10.2,
      },

      satellite: [
        95,
        "Io",
        "Europa",
        "Ganymede",
        "Callisto",
        "Amalthea",
        "Himalia",
        "Elara",
        "Pasiphae",
        "Sinope",
        "Lysithea",
        "Carme",
        "Ananke",
        "Leda",
        "Thebe",
        "Adrastea",
        "Metis",
        "Callirrhoe",
        "Themisto",
        "Megaclite",
        "Taygete",
      ],
    },
  },

  saturn: {
    type: "nasa",

    scale: 0.005,

    ui: {
      info: "Saturn, the sixth planet from the Sun, is famous for its stunning system of rings, which are composed of ice and rock particles. These rings are not only beautiful but also complex, with thousands of individual ringlets. Saturn is a gas giant, primarily composed of hydrogen and helium, and it's the least dense of all the planets in our solar system",

      location: [
        {
          name: "Titan",

          sub_name: "Satellite",

          img: "titan.jpg",

          script:
            "Meet Titan, Saturn's enigmatic moon that's got scientists buzzing with excitement. It's the only moon in our solar system with a thick atmosphere, shrouded in a golden haze. But here's the twist—it's not just air, it's got lakes and rivers of liquid methane and ethane. So, pack your space swimsuits, because Titan is like an extraterrestrial vacation spot with a dash of mystery and a whole lot of wonder!",
        },
        {
          name: "The Great White Spot",

          sub_name: "Storm",

          lat: 23,

          lon: 160,

          img: "great white spot.jpg",

          script:
            "Imagine Saturn throwing a cosmic tantrum – that's the Great White Spot! It's a colossal storm that erupts every few decades, covering the ringed giant in dazzling clouds. Think of it as Saturn's way of showing off its dramatic side. So, when planning your celestial itinerary, be sure to catch this stellar spectacle, because it's a once-in-a-lifetime show in the Saturnian theatre of the skies! ",
        },
        {
          name: "Dragon Storm",

          sub_name: "Storm",

          lat: -26,

          lon: 40,

          img: "the dragon storm.jpg",

          script:
            "Encountering a storm on Saturn that's not only fierce but also breathtakingly long-lasting—the Dragon Storm! It's like a tempest of mythical proportions, swirling around the planet for months on end. With winds reaching up to 300 miles per hour (480 kilometres per hour), this celestial tempest is a must-see spectacle for any space tourist seeking the wild side of Saturn. ",
        },
      ],

      temperature: {
        mean: -140, // it is the average temp at 1-bar pressure level in the atmosphere

        unit: "°C",
      },

      minerals: ["Hydrogen", "Helium"],

      gases: {
        "H₂": 96.3,

        He: 3.2,

        other: 0.5,
      },

      satellite: [
        146,
        "Titan",
        "Rhea",
        "Iapetus",
        "Dione",
        "Tethys",
        "Enceladus",
        "Mimas",
        "Hyperion",
        "Phoebe",
        "Janus",
        "Epimetheus",
        "Helene",
        "Atlas",
        "Pandora",
        "Calypso",
        "Prometheus",
        "Pan",
        "Ymir",
        "Tarqeq",
        "Siarnaq",
      ],
    },
  },

  uranus: {
    type: "nasa",

    scale: 0.005,

    ui: {
      info: "Uranus, the seventh planet from the Sun, is an ice giant known for its unusual tilt. Unlike most planets, Uranus rotates almost perpendicular to its orbit, making it appear to roll along its path around the Sun. This unique orientation gives Uranus its distinct 'sideways' appearance in the solar system. ",

      location: [
        {
          name: "Polar Cyclone",

          sub_name: "Cyclone",

          img: "polar cyclone.jpg",

          script:
            "Uranus, the mysterious ice giant, has a polar surprise for you—a colossal cyclone parked at the North Pole! A never-ending cosmic carousel, whipping winds at over 500 miles per hour (800 kilometres per hour). It's a chilly, mesmerizing swirl that'll leave you spinning with awe. So, when planning your planetary pitstops, don't forget to twirl by Uranus and catch a glimpse of this polar whirlwind! ",
        },
        {
          name: "Uranus Rings",

          sub_name: "ring system",

          img: "uranus rings.jpg",

          script:
            "Did you know Uranus has rings? But they're not your average hula hoops; they're like a set of ghostly, thin bands made of ice and dust. These rings might not be as flashy as Saturn's, but they have their own unique charm, quietly circling the planet in a celestial dance. So, when you swing by Uranus, keep an eye out for these understated cosmic accessories. ",
        },
        {
          name: "Miranda",

          sub_name: "Satellite",

          img: "miranda.webp",

          script:
            "Meet Miranda, Uranus' own moon with a wild makeover. Imagine a patchwork of cliffs and canyons, some deeper than the Grand Canyon! It's a lunar puzzle waiting to be solved, with a terrain that's a real head-scratcher for scientists. So, gear up for an interplanetary adventure on this lunar enigma.",
        },
      ],

      temperature: {
        mean: -225,

        unit: "°C",
      },

      minerals: [
        "HYdrogen",
        "Helium",
        "Water",
        "Ammonia",
        "Methane",
        "Silicate",
      ],

      gases: {
        "CH₄": 2.3,

        "H₂": 82.5,

        He: 15.2,
      },

      satellite: [
        27,
        "Miranda",
        "Ariel",
        "Umbriel",
        "Titania",
        "Oberon",
        "Caliban",
        "Sycorax",
        "Prospero",
        "Setebos",
        "Stephano",
        "Trinculo",
        "Francisco",
        "Margaret",
        "Ferdinand",
        "Perdita",
      ],
    },
  },

  neptune: {
    type: "nasa",

    scale: 0.005,

    ui: {
      info: "Neptune, the eighth and farthest known planet from the Sun, is a distant ice giant with a striking blue hue in its atmosphere due to the presence of methane. It was discovered in 1846 through mathematical predictions and observations, making it the first planet to be found using mathematics rather than direct observation. Neptune's atmosphere is marked by the fastest winds in the solar system, with speeds reaching up to 1,200 miles per hour.",

      location: [
        {
          name: "The Great Dark Spot",

          sub_name: "Storm",

          lat: -12,

          lon: 135,

          img: "the great dark spot.jpg",

          script:
            "Neptune's got a mysterious calling card – the Great Dark Spot! A colossal storm system, kind of like a cosmic hurricane, but on a mega scale. It's like Neptune's own swirling whirlpool of clouds, constantly changing and leaving scientists intrigued. So, when you embark on your interplanetary journey, don't forget to chase this mesmerizing enigma – the Great Dark Spot is Neptune's way of showing off its wild side! ",
        },
        {
          name: "Wizard's Eye",

          sub_name: "Storm",

          lat: -36.5,

          lon: -120,

          img: "wizards eye or dark spot 2.jpg",

          script:
            "Feast your eyes on Neptune's captivating feature, the 'Wizard's Eye.' This cosmic wonder is a gigantic storm, a swirl of clouds with a mesmerizing eye at its centre. It's like Neptune's mystical gaze into the depths of the cosmos. The Wizard's Eye – a spellbinding spectacle in the realm of the ice giants!",
        },
        {
          name: "Triton",

          sub_name: "Satellite",

          img: "triton moon.jpg",

          script:
            "Hey there, future space travellers! Meet Triton, Neptune's peculiar moon that marches to its own beat. It's also one of the few moons that orbits in the opposite direction of its planet's rotation. Triton is like the rebel without a cause in Neptune's moon family",
        },
      ],

      temperature: {
        mean: -200,

        unit: "°C",
      },

      minerals: [
        "Crust : Gaseous hydrogen, Helium, and Methane",

        "Mantle : Water, Ammonia and Methane ice",

        "Core : Silicate and iron-nickel rock",
      ],

      gases: {
        "CH₄": 1,

        "H₂": 80,

        He: 19,
      },

      satellite: [
        14,
        "Triton",
        "Proteus",
        "Nereid",
        "Larissa",
        "Galatea",
        "Despina",
        "Thalassa",
        "Naiad",
        "Halimede",
        "Psamathe",
        "Sao",
        "Laomedeia",
        "Neso",
      ],
    },
  },
  openingIntro:
    "🚀 Prepare for an out-of-this-world adventure where you'll explore the wonders of our Solar System like never before! Whether you're a young astronaut or a curious explorer, this app is your ticket to the cosmos.",
  answer:
    "Mars, often referred to as the Red Planet, is the fourth planet from the Sun in our Solar System. It is known for its distinctive reddish appearance, caused by iron oxide (rust) on its surface.",
};
